//scrolling coins
export const INTIAL_SPEED = 'INTIAL_SPEED';
export const INCREASE_SCROLL_SPEED = 'INCREASE_SCROLL_SPEED';
export const DECREASE_SCROLL_SPEED = 'DECREASE_SCROLL_SPEED';
export const PAUSE_RESUME = 'PAUSE_RESUME';
//main app data
export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const ASSET_SELECTED = 'ASSET_SELECTED';
//chart
export const FETCH_CHART_DATA = 'FETCH_CHART_DATA';
export const FETCH_CHART_DATA_START = 'FETCH_CHART_DATA_START';
export const FETCH_CHART_DATA_SUCCESS = 'FETCH_CHART_DATA_SUCCESS';
export const FETCH_CHART_DATA_FAIL = 'FETCH_CHART_DATA_FAIL';
